jobs:
- job: FormatCode
  displayName: format the code
  steps:
  - script: go fmt
    displayName: Format Code
    continueOnError: true

- job: GoTest
  displayName: Test Code
  steps:
  - script: go test
    displayName: Run go test